// SignToolExt.idl : SignToolExt 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(SignToolExt.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(B69FBB6A-CD60-4CFE-9465-AB13BEFA5C8D),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface ICHandleMenu : IDispatch{
};
[
	uuid(E12EEDAA-8222-408C-AF8F-A5927F067BE0),
	version(1.0),
]
library SignToolExtLib
{
	importlib("stdole2.tlb");
	[
		uuid(56BC0909-03F5-4EF9-AE7B-2846AB28B33E)		
	]
	coclass CHandleMenu
	{
		[default] interface ICHandleMenu;
	};
};

